version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  vectorstore:
    image: "ghcr.io/chroma-core/chroma:latest"
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - is_persistent=TRUE
      - persist_directory=/db
      - anonymized_telemetry=FALSE
      - chroma_server_ssl_enabled=TRUE
    ports:
      - 8000:8000
    volumes:
      - index_data:/index_data
      - ./chroma_store:/db
volumes:
  index_data:
    driver: local
  backups:
    driver: local