# Generated by Django 4.2.3 on 2023-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='site_map',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
