# Generated by Django 4.2.3 on 2023-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_alter_website_site_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='create_site_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='update_site_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='base_site',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='site_map',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
