# Generated by Django 4.2.3 on 2023-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_website_create_site_map_website_update_site_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_scanned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
