# Generated by Django 4.2.3 on 2023-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0004_website_last_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='last_scanned',
        ),
        migrations.AddField(
            model_name='website',
            name='site_last_indexed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='site_map_last_scanned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
