# Generated by Django 4.2.3 on 2023-07-26 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0006_website_site_doc_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('GPT4All-J v1.3-groovy', 'Gpt4All J V1 3 Groovy')], default='GPT4All-J v1.3-groovy', max_length=100)),
                ('temperature', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('limit_time_seconds', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
                ('limit_messages_per_time_per_device', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('not_found_response', models.TextField(default="I'm sorry, I can't find information about your question", max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer', unique=True)),
            ],
        ),
    ]
