# Generated by Django 4.2.3 on 2023-07-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_chatbotconfig_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='collection_name',
        ),
        migrations.AddField(
            model_name='website',
            name='site_collection_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
